$activeBorderColor = rgba(000000ff)
$inactiveBorderColor = rgba(636363ee)

general {
    gaps_out = 0
    border_size = 0
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}
