set -g status-style "bg=default,fg=#272727"
set -g status-left "#[fg=#000000,bg=#d1d1d1,bold] #S #[fg=#272727,bg=default] "
set -g status-right "#[fg=#636363]#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}#[fg=#272727]#h "
set -g window-status-format "#[fg=#636363] #I:#W "
set -g window-status-current-format "#[fg=#000000,bg=#d1d1d1,bold] #I:#W #[fg=#272727,bg=default]"
set -g pane-border-style "fg=#636363"
set -g pane-active-border-style "fg=#000000"
set -g message-style "bg=#ededed,fg=#000000"
set -g message-command-style "bg=#ededed,fg=#000000"
set -g mode-style "bg=#d1d1d1,fg=#000000"
set -g popup-style "bg=#ededed,fg=#000000"
set -g popup-border-style "fg=#636363,bg=#ededed"
set -g menu-style "bg=#ededed,fg=#000000"
set -g menu-selected-style "bg=#d1d1d1,fg=#000000"
setw -g clock-mode-colour "#636363"
